backend:
  name: github
  branch: master
  repo: siddu-nc/netlify-basic
  local_backend:
    url: http://localhost:8081/api/v1
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - widget: "list"
        name: "section"
        types:
          - label: "Blog Feed section"
            widget: "object"
            name: "blog_feed_section"
            fields:
              - name: "blogname"
                label: "Blog name"
                widget: "object"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Created on"
                    name: "date"
                    widget: "date"
                    default: ""
                  - label: "Description"
                    name: "descriptoin"
                    widget: "markdown"
          - label: "News Feed section"
            widget: "object"
            name: "news_feed_section"
            fields:
              - name: "blogname"
                label: "Blog name"
                widget: "object"
                fields:
                  - label: "Name"
                    name: "name"
                    widget: "string"
                  - label: "Created on"
                    name: "date"
                    widget: "date"
                    default: ""
                  - label: "Description"
                    name: "descriptoin"
                    widget: "markdown"
                  - label : "Geo location of store"
                    name: "geo_location"
                    widget: "map"
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: created on, name: date, widget: datetime }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
      - file: "src/pages/documents/index.md"
        label: "owner"
        name: "owner"
        fields:
          - { label: "FirstName", name: "firstname", widget: "string" }
          - { label: "LastName", name: "lastname", widget: "string" }
          - { label: "DateOfBirth", name: "DOB", widget: "date", default: "" }
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "owner-page"}
          - { label: "Description", name: "body", widget: "markdown", required: false}
  - name: "Site Configuration"
    label: "Site Configuration"
    files:
      - file: "src/config/site_config.md"
        label: "Site Configuration"
        name: "site_configuation"
        fields:
        - label : "Header Configuration"
          name: "header"
          widget: "object"
          fields:
          # - { label: "Main title", name: "title", widget: "string"}  
          - { label: "Page Logo", name: "logo", widget: "image", required: true }
          - label: "Navigation Menu"
            name: "nav"
            widget: "list"
            fields: 
            - { label: "Main Menu title", name: "main_menu", widget: "string" }
            - { label: "Has sub menu", name: "has_submenu", widget: "boolean", default: false,required: false }
            - { label: "path", name: "path", widget: "relation", collection: "Page Sections", searchFields: ["title"],    valueField: 'title', displayFields: ['title'], hint: "Don't select if the item has sub menu", required: false
            }
            - label: "Sub Menu Items"
              name: "sub_menu"
              widget: "list"
              fields:
              - {label: "Title", name: "sub_menu_title", widget: "string"}
              - { label: "path", name: "path", widget: "relation", collection: "Page Sections", searchFields: ["title"],  valueField: 'slug', displayFields: ['title'], hint: "Don't select if the item has sub menu"
            }
                

        - label: "Footer Configuation"
          name: "footer"
          widget: "object"
          fields: 
          - label: "Social Media Configuration"
            name: "social_follower"
            widget: "object"
            fields:
              - { label: "title", name: "title", widget: "string"}
              - label: "Follower Logo" 
                name: "logo" 
                widget: "list"
                fields:
                - { label: "Social media name", name: "title", widget: "string"}
                - { label: "Social media icon", name: "image", widget: "image"}
                - { label: "Social media url", name: "url", widget: "string"}
        
        - { label: "Template Key", name: "templateKey", widget: "hidden", default: "site-config"}      
  - name: "Page Sections"
    label: "Page Sections"
    folder: "src/pages"
    path: "{{slug}}/index.md"
    slug: "{{slug}}/index"
    create: true
    fields:
    - {label: "Page name", widget: "string", name: "title"}
    - {label: "Template Key", widget: "hidden",name: "templateKey", default: "section"}
    - {label: "Body Section", widget: "markdown", name: "body"}
    - {label: "slug", widget: "string", name: "slug"}